### ISSUE TITLE
Broken links in Table of Contents

### ISSUE THREAD

**Issue by oles** [lorenzofox3/zora#11]
Creating this just in case it's not know - seems like all titles with emojis in them are broken!

Also, the "CLI" is a lie - for now :)

I'll gladly contribute to a few of the issues I created today if you'd like, @lorenzofox3. 
Just let me know if there's a need for it. Asking just in case if you got something ready just around the corner!

**Comment by lorenzofox3** [comment]
Yes you are right. I was actually working on v2 when it got published on the nodejs weekly, so this is still a work in progress and the readme will be updated with v2

**Comment by oles** [comment]
Excellent, glad to hear - grats on the spot in nodejs weekly as well 👍
