### ISSUE TITLE
module-loader es is not treating my test files as es modules

### ISSUE THREAD

**Issue by mellson** [lorenzofox3/zora#118]
Is it correct that if I run pta with `--module-loader es`, it should treat the test files as es modules no matter the file name? My files have the `.bs.js` suffix because I need compatibility with other dependencies that only work with that suffix. If I manually rename the files to `.mjs`, it works. But it would be great if I could force pta to treat my files as es modules.

**Comment by lorenzofox3** [comment]
> Is it correct that if I run pta with --module-loader es, it should treat the test files as es modules no matter the file name?

Not really, it just tells ``pta`` which zora singleton it should use (cjs, esm). Your package.json should still reflect the repository set up. If your files are effectively written in ESM, you'll have then to add ``type=module`` in your package.json. 

You can refer to the [test/samples](https://github.com/lorenzofox3/zora/tree/master/pta/test/samples) for more details.

**Comment by lorenzofox3** [comment]
in favor of https://github.com/lorenzofox3/zora/issues/155
