### ISSUE TITLE
pta and typescript

### ISSUE THREAD

**Issue by tsnobip** [lorenzofox3/zora#122]
What's the plan for supporting typescript in pta?

Thanks to the modularity of zora I can use other runners so it's definitely not a blocker, so just to know.

Being able to provide the node arguments to `pta` would make it possible for all use cases easily I think.

**Comment by lorenzofox3** [comment]
Hi, in the TS example you have a [npm script](https://github.com/lorenzofox3/zora/blob/master/examples/node-ts/package.json#L18) which uses pta

**Comment by lorenzofox3** [comment]
> Being able to provide the node arguments to pta would make it possible for all use cases easily I think.

Not sure what you mean here, you can always call the pta .bin with node directly: 

``node ./node_modules/.bin/pta some.test.js``

**Comment by tsnobip** [comment]
you're right, easy solution 🤦
