### ISSUE TITLE
Difference to Tape / AVA?

### ISSUE THREAD

**Issue by schoening** [lorenzofox3/zora#123]
Could we get a comparison chart between Tape and Ava, (others too if you like, but those seem to be the obvious similar ones).

Speed is a great thing to have, but I need more than that to convince my enterprise CTO why this framework should be chosen over another 😄.

**Comment by lorenzofox3** [comment]
I don't think you can get such a chart without any bias, and that is not something I/You want. 

Everything depends on your criteria:
* does speed matter ?
* do you favour compos-ability over all included ?
* do you want to run your tests in serie ? 
* in the browser ? 
* does the community size matter ?

Usually that's your job as an engineer to assess a solution against a set of requirements, unfortunately there is no black or white answer. 

You can set up a list of criteria and I will help you to fill the table, to the extend of my knowledge
