### ISSUE TITLE
Pipe error handling (write EPIPE)

### ISSUE THREAD

**Issue by icetbr** [lorenzofox3/zora#136]
Hi, I think you might have mentioned this somewhere. It works fine with pta.

Running

```sh
nodemon test/index.js | tap-spec
```
```js
test(`drawCard`, ({ eq }) => eq(drawCard(
```

where drawCard is not defined, I get

```js
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
```

**Comment by icetbr** [comment]
On further experimentations, it depends on the reporter.

tap-spec FAILS because of
```js
var parser = require('tap-out');
```
where tap-difflet WORKS because of
```js
var parser    = require('tap-parser-yaml');
```
I think you can close this.

**Comment by icetbr** [comment]
On further experimentations, it depends on the reporter.

tap-spec FAILS because of
```js
var parser = require('tap-out');
```
where tap-difflet WORKS because of
```js
var parser    = require('tap-parser-yaml');
```
I think you can close this.

**Comment by lorenzofox3** [comment]
Thanks. I was about to tell, it depends on how the reporter handles bailout message
