### ISSUE TITLE
build npm package

### ISSUE THREAD

**Issue by essential-existence** [lorenzofox3/zora#141]
Hello. How did you build the package "https://registry.npmjs.org/zora/-/zora-5.0.3.tgz" from source? In package.json, I did not find a command that would collect all the code in one file...

**Comment by essential-existence** [comment]
Rollup couldn't find dependencies. In general, I managed without packaging at all. Thank you for your attention.

**Comment by lorenzofox3** [comment]
from the root of the monorepo: 
1. ``npm run install:ci``
2. ``npm run build``

this will give you the various dist folders

you can then go into zora folder (``cd zora``) and run ``npm pack``

(node >= 16, npm >= 8)

**Comment by essential-existence** [comment]
OK, thank you
