### ISSUE TITLE
Zora pta doesn't report anything if there are any pending tests that don't wait for any events

### ISSUE THREAD

**Issue by wokalski** [lorenzofox3/zora#162]
I don't have a minimal zora repro but it's obvious from this:

```
// x.mjs
Promise.all([Promise.resolve(), new Promise(() => {})]).then(() => console.log("hello"))
```

run `node x.mjs` and you won't see hello but the program will terminate successfully. In the case of zora, you will see the program terminate but it won't report anything. Ideally (a 10 star experience) the test runner would execute normally and report and then it would tell me "hey, this and this test is still pending but it's not waiting for anything. It's most likely a bug".

**Comment by lorenzofox3** [comment]
For late assertion collection, you should have an error

```Javascript
import {test} from 'zora';

test('woot', ({ok}) => {
    // setTimeout is not awaited
    setTimeout(() => {
        ok(false)
    });

    ok(true);
})
```

<img width="785" alt="Screenshot 2022-09-02 at 18 18 27" src="https://user-images.githubusercontent.com/2402022/188196393-ab7148d5-9e30-498a-82d0-575fcce9d47f.png">

Hence, I am not sure what you are referring to. Would you mind providing a short repro ?

**Comment by wokalski** [comment]
Its the opposire of late assertion. Create a test that returns `new Promise(() => {}).then(() => t.equal(0, 1))`

**Comment by lorenzofox3** [comment]
Oh I see. Thanks. I'am getting a look at it

**Comment by lorenzofox3** [comment]
Apparently, finding a [broken promise is quite a thing](https://swizec.com/blog/finding-unresolved-promises-in-javascript/#promisekeeper-for-finding-anti-patterns)

The only easy way I can think of (which would be cross platform) is to make the user spec function compete with a timeout function and throw if the timeout wins.

something like [this PR](https://github.com/lorenzofox3/zora/pull/166)

**Comment by wokalski** [comment]
Here's what I'd do:

1. When you register tests add them to a map
2. When they conclude, remove them from the map
3. On `'exit'` hook, print the ones that are not concluded
4. Profit
You don't actually need to know what the state of the promise is, you can solve it reliably on the framework level.

**Comment by lorenzofox3** [comment]
Actually that's not that simple. There is only an exit hook in a nodejs environment (and Deno) but not in the browser. You can't either add this check after the reporting stream as it is simply broken (the code after won't run). 

I think I'll rather go for test timeout which adds anyway a nice to have assertion
