### ISSUE TITLE
Top level function does not support async/await

### ISSUE THREAD

**Issue by WalasPrime** [lorenzofox3/zora#19]
Currently the top level import does not return a valid Promise to use with async/await. Using nested tests seem to work fine.
```javascript
const test = require('zora');
(async () => {
	console.log('1');
	await test('My long test', async t => {
		console.log('2');
		await t.test('My long subtest', async t => {
			console.log('3');
			await new Promise(res => setTimeout(res, 1000));
			console.log('4');
		});
		console.log('5');
	});
	console.log('6');
})();
```
Current output:
```
1
2
3
6
TAP version 13
# My long test
# My long subtest
4
5
1..0
# ok
```
Expected output (approximate, only order of numbers matters):
```
1
2
3
TAP version 13
# My long test
# My long subtest
4
5
6
1..0
# ok
```

**Comment by lorenzofox3** [comment]
Yes you are right, you need to wrap your tests within a top-level test clause if you want to make them inter dependent and change the default control flow. 
That's actually expected
