### ISSUE TITLE
testing a callback function

### ISSUE THREAD

**Issue by davelandry** [lorenzofox3/zora#2]
I have a Class that renders elements to a page, and I am trying to run a test that runs assertions after the drawing has completed. Here is my code:

```js
import zora from "zora";
import {Rect} from "d3plus-shape";

export default zora()
  .test("Shape/Rect", assert => {

    new Rect()
      .data([{id: "test"}])
      .render(() => {

        assert.equal(document.getElementsByTagName("svg").length, 1);

      });

  });

```

When running using tape-run, zora never sees the assertion inside of the render callback. In raw tape, it will wait for `assert.end()` to be manually triggered. Are there any recommendations on how to do this with zora?

**Comment by lorenzofox3** [comment]
If your function is a Thunk, [https://github.com/tj/co](co) can "yield" it for you, or even better you can promisify your api :) 

```Javascript
const zora = require('zora');

zora()
  .test('thunk function', function * (t) {
    let counter = 0;

    const thunkFunctionToTest = function (cb) {
      counter++;
      cb();
    };

    yield thunkFunctionToTest;

    t.equal(counter, 1);
  })
  .run();
```

**Comment by davelandry** [comment]
Perfect, thank you @lorenzofox3! I'm a little unfamiliar with the whole generator/yield thing, so you example helped me immensely. For anyone stumbling upon this in the future, here's my updated (working) code:

```js
import zora from "zora";
import {Rect} from "d3plus-shape";

export default zora()
  .test("render callback", function *(assert) {

    function yieldFunction(cb) {

      new Rect()
        .data([{id: "test"}])
        .render(cb);

    }

    yield yieldFunction;

    assert.equal(document.getElementsByTagName("svg").length, 1);

  });
```
