### ISSUE TITLE
proposal: output proper exit codes

### ISSUE THREAD

**Issue by thisguychris** [lorenzofox3/zora#20]
I like how fast and light `zora` is, would it be possible for it to output proper exit codes? Or is that job of at the test-runner?

1. test case:
```js
// wat.js
const test = require('zora')

test('what', t => {
    t.ok(false)
})
```

2. what I think should happen

```bash
$ node wat.js
$ echo $status
1
```

3. what is happening instead:

```bash
$ node wat.js
$ echo $status
0
```

**Comment by lorenzofox3** [comment]
I had already thought about it. But exit code are platform specific and more over some test runners do not want those exit codes (for further processing), so I would say it is the job of the test runner. 

However good news: with TAP you already have a lot of [processor that can output the "proper" exit code](https://www.npmjs.com/search?q=tap%20exit).

For continuous integration platform I personally use
- [tape-run](https://github.com/juliangruber/tape-run) if I need the tests to be run in a browser
- [tape-diff](https://www.npmjs.com/package/tap-diff) for node

My "test runner" is simply node or the os itself :) and that gives you a lot of flexibility.

For example
``rollup -c path/to/config | tee ./debug.js | node | tap-diff``

the above command will bundle (or concat) all test files, create a debug file pipe it to a node process and ask tap-diff to process the output and set the proper exit code.

At some point, it might make sense to create a more opiniated test runner on top of zora to do that but I personally prefer the flexibility of small processes and believe zora should stay simple :)

**Comment by TehShrike** [comment]
The problem with "node as a test runner" is that `node test-file.js` returns 0 even if tests fail.  Even though I can see how it makes sense, this is not what I expected - it means that on several of my repos, TravisCI will always show green, even if tests have failed.

**Comment by lorenzofox3** [comment]
@TehShrike yes I understand the point but it is so easy and more flexible to then use unix pipe command that I see no added value to use node specific code (keep in mind that some people use the browser as test runner)

For example your package json can be 

```
devDependencies:{
  zora:"*",
  tap-diff:"*"
},
scripts:{
  "test":"node myTestFile | some-dev-adapted-tap-reporter",
  "test:ci": "node myTestFile | tap-diff" // or any other
}
```
and your travis build will be all fine (failing when it has to, passing when it has to)

**Comment by thisguychris** [comment]
@lorenzofox3 possible suggestion, what if we use a flag to tell it's running against node, and that way you can output the correct exit code, eliminating the need to pipe anything just for exit code in CI (less deps).

Something like this:
`node test-file.js --node`

That or just update the README and tell people it's not giving proper exit codes. People like @TehShrike had already adopted `zora` on a number of his repos, only to find out it was giving him false positive because CI sees it's always returning zero exit code.

Super clean codebase by the way! @lorenzofox3

**Comment by lorenzofox3** [comment]
> @lorenzofox3 possible suggestion, what if we use a flag to tell it's running against node, and that way you can output the correct exit code, eliminating the need to pipe anything just for exit code in CI (less deps).

> Something like this:
node test-file.js --node

The problem whether you read it from a flag or not is that at some point we would need in zora something like

```Javascript
if(typeof process !== 'undefined'){
   const code = failing ? 1 : 0;
   process.exit(code);
}
```

My experience has taught me this can be problematic for module bundlers for example: when they parse that branch they must understand this branch is only relevant for a given environment. It is even more troublesome as `process` is a native module and they might need to provide a shim for browsers, etc.

I am not saying that is not doable but it is quite a lot of trouble compared to adding a development dependency

> That or just update the README and tell people it's not giving proper exit codes. People like @TehShrike had already adopted zora on a number of his repos, only to find out it was giving him false positive because CI sees it's always returning zero exit code.

I agree although most of the time as you run your tests locally first you should have few false positives and update your ci setup little by little as you update the code in your repos

I should definitely update the Readme though. Thanks for the advice

**Comment by thisguychris** [comment]
@lorenzofox3 this one just bit me, ![text should fail here](https://monosnap.com/image/MsyZiGzqAxDbsfVUKo0ApAHMLLgjsM.png "text should fail here")

There was a syntax error, but the test returned zero test ran and it reported status zero and piped to `tap-diff` which should be wrong, since if your program can't run it should report in the test runner?

**Comment by lorenzofox3** [comment]
It seems to me you have an uncaught error, zora should `bail-out` re throws the error then it depends on how the tap-reporter downstream deals with it. 

That is the expected behavior for me at least. 

There is a remaining issue though: the process does not exit with 1. 
But this is due to node problem: when zora re throws the error it "produces" an unhandled promise rejection. 
This should be fixed soon (see the deprecation warning) though

<img width="743" alt="screen shot 2018-09-27 at 1 32 33 pm" src="https://user-images.githubusercontent.com/2402022/46163897-7b859f80-c25a-11e8-95a9-40235fee3ca2.png">

**Comment by TehShrike** [comment]
This should probably be moved to a new issue - it looks like the root problem for @thisguychris's latest report is that a syntax error caused zora to spit out 0 passing and 0 failing tests, which the downstream tap reporter interpreted as a passing test.

The fix for this would probably be to say that if a script throws an error before zora spits out any test output, zora should spit out something like

```
not ok 1 - script threw an error before any tests were started
```

**Comment by lorenzofox3** [comment]
I don't agree, according to to TAP specs, it should `bail-out` which I believe it does (see my screen shot). 

> The fix for this would probably be to say that if a script throws an error before zora spits out any test output, zora should spit out something like ``not ok 1 - script threw an error before any tests were started``
 
Moreover your test point would not reference any actual test

If tap-diff does not handle bail out it is a different story...

Maybe @thisguychris you could provide a sample to reproduce so we can be sure we are talking about the the same thing :)

**Comment by TehShrike** [comment]
Oh yup, you're right `Bail out!` is correct.

**Comment by TehShrike** [comment]
@thisguychris I think we're waiting for you to post an example test that reproduces the issue

**Comment by TehShrike** [comment]
This should probably be re-opened?

**Comment by lorenzofox3** [comment]
I don't think so, the problem comes from the tap processor the stdout stream is piped to (tap-diff?). 
If you try to run the provided program without any processor, well node will crash as it is invalid javascript

**Comment by TehShrike** [comment]
You're right.  @thisguychris I can't reproduce the issue you showed.  When I clone the latest version of zora and try to run the test with bad syntax as in your example, I just get

```
joshduff @ Joshs-Mac-mini : ~/code/zora (master)
$  node bug-20.js 
/Users/joshduff/code/zora/bug-20.js:5
}
^

SyntaxError: missing ) after argument list
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

I don't see any message about tests passing, and node exists with a non-zero exit code.

**Comment by lorenzofox3** [comment]
@thisguychris, I think you don't fully understand: 

1. zora does not handle exit codes for the following reasons:
- exit codes are platform specific (you don't have such a thing in the browsers for example)
- zora does not have any opinion on whether a failing test should result in a different exit code. Technically the test program may has run well (completed to its end) whereas you have some failing cases so should it really exit with something other than 0 ? It therefore gives the responsibility to the reporting process. I suggested tap-diff but they are plenty of others.

This behavior is expected and I will unlikely change.

2. Your case is a bit uncommon, as you have invalid Javascript passed to node (how so?). By default in Unix if you use a pipe (`|`) the exit code will be the one emitted by the last process of the pipe. So in your case when nodejs fails to read your program it is silently ignored . 
The stdout passed to tap-diff process is some garbage (or empty) it can not understand which it interprets has no test has run. tap-diff has chosen to report this as a success others reporters processes might choose to do it differently.

Note: on unix you can make sure your command fails if any of the process in the pipe fails

``set -o pipefail; node ./invalid.js | tap-diff; echo $?;`` will return 1

**Comment by thisguychris** [comment]
@lorenzofox3 
1. I am getting where you are coming from, it's hard to bake in code where it assumes two different environment. What I was suggesting was using a flag (--node), so that's basically telling it's opt-in to user. Which basically remove's the need to write code for detection. Anyway, I respect your opinion if you don't want it add it.

2. My case is not uncommon, but I'm not here to argue. Using exactly your code on your comment:
https://github.com/lorenzofox3/zora/issues/20#issuecomment-425181915

Yields false positive in what you suggested - tap-diff. So even if you intentionally throw an error, the test still pass. 😐

![Alt text](https://monosnap.com/image/4Vkk4D8rLg5TIRWGglFv4fS1eb2wee.png)

**Comment by lorenzofox3** [comment]
> Yields false positive in what you suggested - tap-diff. So even if you intentionally throw an error, the test still pass. 😐

You are right, tap-diff does not handle bail out directive properly.

>     2. My case is not uncommon, but I'm not here to argue.

I am actually interested in that part (not the argument part : ) ), I would like to know how the devs use zora.
My assumptions is the following: most of the developers use IDE (or linters) which perform static analysis so it is very rare to have code with syntax error.

You said it is not that uncommon Is it because you are doing some sort of file watching so you file is in between two state ? or something else ? can you tell me more on the circumstances it happens. 

Or are simply you referring to any error (not only invalid syntax) like in the comment ?

Thanks

**Comment by thisguychris** [comment]
> Or are simply you referring to any error (not only invalid syntax) like in the comment ?

I'm referring to any error like in the comment. In our case, the linting was disabled in the CI since like the assumption you have, "most developers have IDE / linting tools" anyway. Turns out not all of them :D (the developer had his linting disabled by default). It bit us.

**Comment by TehShrike** [comment]
I just ran into a test failure that fails properly locally but bails out in the CI environment.

Has anyone found a script that returns a correct status code on bail out?

**Comment by lorenzofox3** [comment]
@TehShrike what is "the correct status code on bail out" ? 

I am not sure to understand the question correctly.

The differences between your local environment and a CI setup can indeed lead to different output: missing database, different node version, different OS, etc.

If you have found a problem with zora, maybe you can open a new issue with more details so I can help to fix the issue.

**Comment by TehShrike** [comment]
I opened a PR to change [tap-exit-code](https://github.com/m59peacemaker/node-tap-exit-code) to return status code 1 on bail out, so version 2 of that library will get the job done for anyone having the same issue.

**Comment by TehShrike** [comment]
[`tap-exit-code`@2](https://github.com/m59peacemaker/node-tap-exit-code) and [`tap-color`@1.2](https://github.com/laat/tap-color) are both patched to set the correct status code on bail out.
