### ISSUE TITLE
Custom assertions?

### ISSUE THREAD

**Issue by RedHatter** [lorenzofox3/zora#25]
It would be nice if we could extend the assertions object to provide custom assertions.

**Comment by lorenzofox3** [comment]
you can simply decorate your spec function: 

```Javascript
const withFooAssert = specFn => t => specFn(Object.assign(t, {
  foo(actual, expected, description = 'foo !') {
    const assertResult = {
      pass: Object.is(actual, expected),
      actual: actual,
      expected: expected,
      description,
      operator: 'foo'
    };

    this.collect(assertResult); // COLLECT RESULT
    return assertResult;
  }
}));

// and then when you write your tests:

test('foo bar bim', withFooAssert(t => {
   t.foo('var','bar');
}));
```

You can centralize it if you find it troublesome to write the decorator on each test:

```Javascript
const test = require('zora');

module.exports = (description, spec) => test(description, withFooAssert(spec));
```
And require this function instead of zora

**Comment by RedHatter** [comment]
Snapshot testing jest style that compares a string against a cached version and visual snapshot testing using pixelmatch that compares an image against a cached version.

I've run into a bit of an issue with the visual snapshot. I have three values I need to I need to display when the assertion fails, expected, actual, and the difference. The collect function doesn't have any place to put the difference value. Could you either add an additional field (`reason` maybe?) or even better have the tap printer print all fields in the object?
