### ISSUE TITLE
[community] Remove BDD style ?

### ISSUE THREAD

**Issue by lorenzofox3** [lorenzofox3/zora#28]
I am currently working on a new version and I was thinking to remove BDD style to simplify code. Is anyone actually using it or not ?

**Comment by oles** [comment]
My guess is that those who prefer BDD uses tools meant for exactly that :)

**Comment by lorenzofox3** [comment]
Yes that what I was thinking too. Moreover most of tap reporters are at the end tightly coupled to tape format and do not understand indented tap stream (except mocha-tap-reporter which goes with node-tap).
I personally like indented tap streams which help structure and group tests but I do not really care about fancy reports. I rather prefer something that summarize the tests correctly.

**Comment by oles** [comment]
Indeed. Fancy reports are more suited to something not as minimal as this.

**Comment by TehShrike** [comment]
I do like the ability to nest different test scopes, though I don't use it often.
