### ISSUE TITLE
rollup recipe without the need for /test/dist?

### ISSUE THREAD

**Issue by binarykitchen** [lorenzofox3/zora#3]
first, zora looks great, keep it going!

when I read at https://github.com/lorenzofox3/zora#as-part-of-ci-example-with-rollup I have a couple of constructive criticism questions:

-instead of importing each single test file inside `test/index.js`, can't we have a wildcard-based solution? so that we do not have update `test/index.js` each time we add a new test file?

-is there a solution to have the `/test/dist` part in memory instead so that it does not get written on disk which is imo not needed?

enuff for now :) tell me what you think of that?

**Comment by lorenzofox3** [comment]
Hi, 
zora is "only" a test harness (like jasmine or tape for example)

What you are talking about is more the job of a test runner. Technically nothing prevent you to make every test file a runnable test on its own and ask Karma, Jest, gulp, grunt, fs or whatever to monitor changes/ bundle/ transpile/ etc  and execute them under specific conditions.

**Comment by binarykitchen** [comment]
@lorenzofox3 well, i landed here from the other thread https://github.com/juliangruber/tape-run/issues/35 on rollup and am looking for tips/recipes.

and since you have rollup examples in your readme, i think my question is legit to have improved rollup examples?

**Comment by lorenzofox3** [comment]
Hi, 

It is sure legit. However I find it difficult to provide more recipes other than the ones I use as these are very particular to one's workflow and the tools one will use. I can try to find one with your particular use case if your give me more informations: 
1) do you use a build tool ?
2) do you use a particular test runner or test framework ?
3) do you need code transpilation (or to create a bundle)
4) what platforms do you target ? (node, modern browsers? legagy browsers ?) 

That's a lot of parameters which will make a solution more or less adapted. The whole idea of zora is to be as less opiniated as possible 

I for example don't use much build tools other than nodejs itself (and npm scripts) so for your example I would probably create a runTest.js file which would use [fs.watch](http://devdocs.io/node/fs#fs_fs_watch_filename_options_listener) and run rollup on the callback to output the result in stdout which I would pipe into tape-run (to avoid to write into the disk if you thinkg that's too much of a trouble).

``rollup test/entry.js | tape-run``

**Comment by binarykitchen** [comment]
1. no build tool. going to dump gulp in favor of vanilla nodejs, yarn and rollup
2. atm using browserify, tape and tape-run, but intending to switch to rollup and considering using zora + tape-run or something like that (that's why i am asking you for recipes)
3. dont need to create a bundle for tests but yes, it's for a library so will need a bundle at the end (see https://github.com/binarykitchen/videomail-client, it's the dist folder)
4. modern browsers only

already am in progress to migrate from gulp to rollup in this WIP branch https://github.com/binarykitchen/videomail-client/tree/feature/rollupjs

all i am wanting is a recipe for making `rollup test/entry.js | tape-run` possible without the need to bundle test files into `/test/dist` ... yeah, output them to stdout instead maybe.

**Comment by lorenzofox3** [comment]
Hi 

I have provided [some of my recipes](https://github.com/lorenzofox3/zora-recipes)
There is also a video on youtube for a live example. 

it features
1. a CI mode that stream rollup bundle into tape-run to get proper exit code (without writing on the disk)
2. A "dev" mode which allows me to quickly run my test in a browser as the bundle is served by a file server. Using the Chrome workspace I am also able to edit the source file from the browser while debugging the tests.

Let me know what you think.

**Comment by binarykitchen** [comment]
@lorenzofox3 awesome, i like that simple recipe for the CI mode. nice recipe, thanks heaps. why not link it with the official zora documentation for anyone else?

btw, the video link does not seem to work. otherwise don't have anything else to add right now. still am stuck with other rollup issues i am having. like `'default' is not exported by 'node_modules/global/document.js'` ... trying to crack them first.

thanks again!

**Comment by lorenzofox3** [comment]
[link](https://youtu.be/FqhyclpUI-g) fixed

**Comment by TehShrike** [comment]
[glob-module-file](https://github.com/TehShrike/glob-module-file) works well for piping a bunch of zora test files to be all run at once.

```sh
glob-module-file --pattern="**/*.test.js" --format=cjs | node
```

```sh
glob-module-file --pattern="**/*.test.js" --format=cjs | browserify | tape-run
```
