### ISSUE TITLE
New named export in v3

### ISSUE THREAD

**Issue by jmakeig** [lorenzofox3/zora#32]
It looks like v3 changes the module layout to use named exports, instead of the [previous default export](https://github.com/lorenzofox3/zora/blob/b9c2d608c80a48edee49e48a766ec4a73098f3cd/dist/zora.es.js#L556), such that the `import` statement now needs 

```js
import { test } from 'zora';
```

rather than 

```js
import test from 'zora';
```

as documented.

Or am I missing something?

**Comment by lorenzofox3** [comment]
yes you are right. I am still in the process of writing the documentation. I am surprised you get v3 on install though should be the @next release. I must have made an error

**Comment by jmakeig** [comment]
Nope, I just did an `npm install zora --save-dev` yesterday and my `package-lock.json` looks like:

```json
"zora": {
  "version": "3.0.0-0",
  "resolved": "https://registry.npmjs.org/zora/-/zora-3.0.0-0.tgz",
  "integrity": "sha512-Xhyi2MN2gslAxpgBxQLER79fKSBp99QaikR4g29tWQz7ilPLrIrOOCXgjv94PbcEuJGr/cpH3+pVkJd7u9o/MQ==",
  "dev": true
}
```

**Comment by jmakeig** [comment]
Should I revert back to 2.0.1, for the time being?

**Comment by lorenzofox3** [comment]
I think I made a mistake somewhere. 

> Should I revert back to 2.0.1, for the time being?

I think API is pretty stable and you should not expect big breaking changes but new version remains undocumented

**Comment by jmakeig** [comment]
Gotcha. I was going to do a PR, but the master branch didn’t look like what’s published to npm. I’ll revert back to 2.0.1 for now and eagerly await the official 3.0 release. 

Thanks for your continued work. Let me know how I can help.

**Comment by lorenzofox3** [comment]
What was your PR about so I can maybe include it in version 3

**Comment by jmakeig** [comment]
Ha! To fix the docs.
