### ISSUE TITLE
zora@3 is live on npm and appears broken

### ISSUE THREAD

**Issue by TehShrike** [lorenzofox3/zora#33]
I ran `npm i zora` today and got `zora@3.0.0-0`.  It doesn't have a default export, so `import test from 'zora'` failed, which is how I figured out something was up.

The readme doesn't seem to be updated in the v3 branch, so I'm guessing that v3 isn't ready for release yet?  You might want to deprecate the v3 release on npm or something.

**Comment by lorenzofox3** [comment]
yes you are right see( #32 )

**Comment by lorenzofox3** [comment]
thanks for the tip on deprecate !

**Comment by TehShrike** [comment]
I think you deprecated the whole package - you can deprecate just version `3.0.0-0`, that would probably be better :-x

**Comment by TehShrike** [comment]
You can un-deprecate all of the non-3.0.0-0 versions by running `deprecate` again with a blank message: https://docs.npmjs.com/cli/deprecate

**Comment by lorenzofox3** [comment]
Weird again I had deprecated it using ``npm deprecate zora@3.0.0-0 "Still in beta, no harm to use it but should have been tagged as @next"``. 

Anyway thanks for you help
