### ISSUE TITLE
[community] v3 review

### ISSUE THREAD

**Issue by lorenzofox3** [lorenzofox3/zora#35]
V3 is almost there ! in beta now, you can install it with ``npm install zora@next`` and start to review it.
The documentation is available in the readme of the branch v3.

Main changes are:
- target modern engines with use of ``for await`` and  async generators
- is in typescript (#21  )
- still start automatically to report by default but it can also be controlled (#26 ) 
- there is more than a single default export (to avoid breaking changes in the future): the single export was introduced to be as close as possible as tape. It did not bring more traction in the project so I believe we can go with a more flexible approach
- Simplification of the assert library and more aliases for syntax sugar
- Reporters and assert library is friendlier for custom assertion (#25 )
- _skip_ is implemented (#16 ) (only will come in a node specific test runner)

I am also working on small test runner specific to node but this can be aside

Any comment appreciated !

@styfle, @TehShrike @jmakeig

**Comment by corbinu** [comment]
@lorenzofox3 Tried it out and I am getting typescript build errors:

```
✖ 3 problems (0 errors, 3 warnings)

node_modules/zora/dist/declarations/interfaces.d.ts:78:46 - error TS2304: Cannot find name 'AsyncIterable'.

78 export interface TestHarness extends Assert, AsyncIterable<Message<any>>, Counter {
                                                ~~~~~~~~~~~~~

node_modules/zora/dist/declarations/interfaces.d.ts:98:14 - error TS2304: Cannot find name 'AsyncIterable'.

98     (stream: AsyncIterable<Message<any>>): Promise<void>;
                ~~~~~~~~~~~~~

node_modules/zora/dist/declarations/interfaces.d.ts:106:31 - error TS2304: Cannot find name 'AsyncIterable'.

106 export interface Test extends AsyncIterable<Message<any>>, TestResult, Counter {
                                  ~~~~~~~~~~~~~
```

**Comment by lorenzofox3** [comment]
@corbinu I think AsyncIterable are still under ``esnext`` for typescript. In your tsconfi file you need to add it as lib

**Comment by corbinu** [comment]
@lorenzofox3 Thanks that helps I had 2018 in there. Do I have to use rollup now on a node project if I want the tests in multiple files? 

I really liked the old system where you could export a plan. Any chance of bringing back something where you wrap the tests in a file in a plan and export them up to an index file?

**Comment by lorenzofox3** [comment]
> @lorenzofox3 Thanks that helps I had 2018 in there. Do I have to use rollup now on a node project if I want the tests in multiple files?

no, just ``require`` your test files in some entry point such ``./test/index.js``, node will concat the files for you.

> I really liked the old system where you could export a plan. Any chance of bringing back something where you wrap the tests in a file in a plan and export them up to an index file?

You can still do it (cf previous comment). If you want some more "logic grouping" you can export a sub test:

```Javascript
// ./test/foo.js
module.exports = t => {
    t.test('foo test', t => {
     t.ok(true)
    })

    //etc
}

// ./test/index.js
const {test} = require('zora');

test('./foo.js', require('./foo.js'))

// etc
```

You can of course use ``fs`` or some globby module to automatically load all your test files in the index. Congratulation you have built your first test runner on top of zora :)

**Comment by corbinu** [comment]
@lorenzofox3 Sorry to keep having so many questions. That works however I can't seem to import the type definitions

<img width="722" alt="screen shot 2019-02-03 at 4 38 46 pm" src="https://user-images.githubusercontent.com/533625/52185252-5689d600-27d2-11e9-8ed1-de69e0185f9d.png">

**Comment by lorenzofox3** [comment]
``TestFunction`` is not exported, it is used internally

**Comment by corbinu** [comment]
Ok how am I supposed to type these tests then?

**Comment by lorenzofox3** [comment]
> Ok how am I supposed to type these tests then?

what ``these tests`` refer to ? I am not sure to understand your question.  

The type system shall know what ``test`` function  expect even though its argument types are not exported:

compilation error:
<img width="661" alt="type error on zora test method" src="https://user-images.githubusercontent.com/2402022/52284374-47219e80-2932-11e9-8641-f083b1a2a17f.png">

type inference:
<img width="530" alt="type inference with zora test" src="https://user-images.githubusercontent.com/2402022/52284429-5e608c00-2932-11e9-9428-0a11a0e5bfe8.png">

If you wish to build on top of zora and manipulate ``SpecFunction`` on your code base, indeed it might be easier if zora was exposing this type and at some point it might make sense to expose it as it is a _public argument_  but it should not be blocking:

You can create in your code base your own interface with the same signature and actually it would be probably be safer. Your code shall be responsible to call the zora functions with the appropriate types and typescript will enforce it. If you blindly copy types around you might be in trouble as any changes in zora types will force you to change your api too. Whereas if you use your own types, the only part you would have to change would be the _private_ part of your code which provide valid arguments to zora api.

Maybe you could provide a small repo setup so I can understand your problem.

**Comment by corbinu** [comment]
@lorenzofox3 The problem is since I have my tests in separate files I need to import just the type. I have never seen TypeScript project withhold the types to avoid breakage before. Usually I see that as the way to upgrade a TypeScript dep is to depend on the types to show me the breakage. If this is the not a priority I understand.

**Comment by lorenzofox3** [comment]
@corbinu I published a new version with exported types !

**Comment by corbinu** [comment]
Perfect working great!
