### ISSUE TITLE
Example of using tape as a runner

### ISSUE THREAD

**Issue by EdwardIrby** [lorenzofox3/zora#38]
Hi really enjoy using this library. I had fun this past week trying it out in the browser, and as demonstrated in the readme and comparing it to ava and riteway. I did run into some challenges but finally settled on a config I think is best  for my current projects.

I wanted to share this setup that's working for me with the zora community.  I hope to test with puppeteer either tonight or tomorrow night.

```json
{
  "scripts": {
    "test": "npx -n '-r esm' tape src/**/*.test.js",
    "test:coverage": "c8 npx -n '-r esm' tape src/**/*.test.js",
    "report": "c8 report"
  },
  "devDependencies": {
    "c8": "latest",  
    "esm": "latest",
    "tape": "latest",
    "zora": "latest"
  }
}
```

Additionally I also wrote a little helper function to help express my test output better. I think others might enjoy it if they concur Eric Elliot's [views on testing](https://medium.com/javascript-scene/what-every-unit-test-needs-f6cd34d9836d)

```js
import { test, equal } from 'zora';

export { test };
export const assert = ({
  given,
  should = '',
  actual,
  expected,
}) => equal(
  actual, expected,
  `Given ${given}: should ${should}`,
);
```

**Comment by lorenzofox3** [comment]
thanks for sharing !
