### ISSUE TITLE
Sourcemap support for stacktrace reporting

### ISSUE THREAD

**Issue by jmakeig** [lorenzofox3/zora#48]
I’m struggling with how to get the `at` output in failing tests to use sourcemaps to display stacktraces in a transpiled environment. I can’t tell if this is a problem with my setup or Zora or just Node more generally.

I was hoping that running Node with [source-map-support](https://www.npmjs.com/package/source-map-support) would magically address this, but I don’t see a difference running with or without it.

My tests and code are authored in TypeScript. I use rollup with the the `rollup-plugin-typescript2` and `rollup-plugin-multi-entry` plugin to respectively transpile and concat all of my tests into a single ES2015 module output. 

## `test.config.js`

```js
import multiEntry from 'rollup-plugin-multi-entry';
import nodeResolve from 'rollup-plugin-node-resolve';
import typescript from 'rollup-plugin-typescript2';

export default {
	input: 'src/**/*.test.ts',
	output: {
		format: 'esm',
		file: 'dist/tests.js',
		sourcemap: true
	},
	plugins: [
		multiEntry(),
		nodeResolve(),
		typescript({
			typescript: require('typescript')
		})
	]
};
```

## `tsconfig.json`

```json
{
	"compilerOptions": {
		"target": "es2015",
		"module": "es2015",
		"sourceMap": true,
		"noEmit": true,
		"strict": true,
		"moduleResolution": "node",
		"esModuleInterop": true,
		"inlineSourceMap": false
	}
}
```

## Output 

From the command line and the browser the tests run fine, other than the `at` value reporting the stacktrace of the transpiled/concatenated code.

```shell
npx rollup -c test.config.js && npx tsc && node -r esm -r source-map-support/register dist/tests.js
```

```
TAP version 13
# asdf
ok 1 - EQUAL
# another
not ok 2 - B
  ---
    actual: "b"
    expected: "c"
    operator: "equal"
    at: " Generator.next (<anonymous>)"
  ...
1..2

# not ok
# success: 1
# skipped: 0
# failure: 1
```

Note the `at: " Generator.next (<anonymous>)"`. Running the same suite in the browser the output is `at: "promiseReactionJob@[native code]"`.

The behavior is the exact same as without the `-r source-map-support/register`. 

Whose responsibility is it to read the sourcemap to translate stacks in a Node environment? The browser console does this automatically to traverse resources, but the `at` value in the TAP output always seems to be calculated without any knowledge of the sourcemap. 

Am I missing something in my build configuration? Any guidance would be much appreciated.

**Comment by jmakeig** [comment]
It looks like running the tests through `esm` threw `source-map-support` off. Using `output.format = 'cjs'` seems to work.

**Comment by jmakeig** [comment]
[Here’s](https://gist.github.com/jmakeig/a34436dbda60908acf47d9f19e266ce5?ts=2) what I came up with, if anyone is interested. Feedback is much appreciated.

**Comment by lorenzofox3** [comment]
Thanks @jmakeig 
If your target is node (I see you run the tests with node) you probably do not need the bundler
I usually have the [following setup](https://gist.github.com/lorenzofox3/a8fe20b726038f4cb4519c8c224a8163). You only need to compile from typscript including sourcemaps with the compiler option, then run your entry point with node calling esm before
``node -r esm ./spec.js``

Note I have also a dev script which watch the typscript source and compile on changes so whenever I run ``npm t`` I test the latest version. You can probably run the test script in parallel with nodemon if you wish to run the test in every change as well:

``npm run compile -- -w & nodemon ./spec.js`` 

output: 

<img width="606" alt="Screenshot 2019-10-08 at 16 29 11" src="https://user-images.githubusercontent.com/2402022/66430802-cf3bd480-e9e8-11e9-864a-97b2e1372502.png">
