### ISSUE TITLE
Stack trace when the test bails out?

### ISSUE THREAD

**Issue by saghul** [lorenzofox3/zora#49]
Hey there! 👋 

Very nice project! 🙏  I'm using it in my QuickJS experiment here: https://github.com/saghul/quv/blob/master/tests/t.js and I noticed that when I make a typo or something in a test, the output is just that the test bailed out, but I get no stack trace. Have I configured the harness wrong or something?

Cheers!

**Comment by lorenzofox3** [comment]
Normally any error is one of your test functions is re thrown (as a rejected promise) whereas any error outside would simply make the process crash. So I suspect you are swallowing the error somewhere in your promise chain.

I have not dig up much into your repository but I saw you create yourself the harness with a somehow custom test-runner. 

I have set up something similar in the [following gist](https://gist.github.com/lorenzofox3/1acbffa60e18298906cd175efe981d97)

Let me know if it helps

**Comment by saghul** [comment]
Thanks for this, it is inmensely helpful!

> So I suspect you are swallowing the error somewhere in your promise chain.

Ah, I think we hit the jackpot. Currently QuickJS has no way to add a unhandled promise hook, so I'm a bit blind here.

I'll dig into it, but this certainly puts me in the right direction!

**Comment by lorenzofox3** [comment]
I am going to close this one as it does not seem to be a problem.

**Comment by saghul** [comment]
I wasn't catching the promise in `harness.report` 🤦‍♂
