### ISSUE TITLE
generators aren't supported by buble

### ISSUE THREAD

**Issue by hollowdoor** [lorenzofox3/zora#5]
I was wondering if it's possible to have tests alternatively without generators. While still being able to return a promise, but without the `*`. `buble` es2015 transpiler doesn't support generator transpilation.

This would also be good for the new `async` functions that are coming out soon.

**Comment by lorenzofox3** [comment]
you can [turn off genrator transformation](https://gitlab.com/Rich-Harris/buble/issues/71).It will not harm your tests as now almost [every browser support generators](http://kangax.github.io/compat-table/es6/#test-generators1) natively. 

> This would also be good for the new async functions that are coming out soon.

yes this is going to happen soon as anyway generators are currently used by [co](https://github.com/tj/co) to have a async/await flow

**Comment by hollowdoor** [comment]
> "turn off generator transformation"

I didn't want to do that. Thanks anyway.
