### ISSUE TITLE
Typescript + ES6 testing

### ISSUE THREAD

**Issue by munrocket** [lorenzofox3/zora#57]
This lines doesn't works with typescript
```javascript
// test/test.ts
import { test } from 'https://cdn.jsdelivr.net/npm/zora@3.0.3/dist/bundle/module.js';
import { test } from '../node_modules/zora/dist/bundle/index.mjs';
```
I can only compile it with `import { test } from 'zora'` but after that node can't find ES6 module.

**Comment by munrocket** [comment]
I am fixed this with rollup.

**Comment by lorenzofox3** [comment]
please have a look at the [typescript example](https://gist.github.com/lorenzofox3/a8fe20b726038f4cb4519c8c224a8163)

**Comment by munrocket** [comment]
Just a quick hack with `esm`, but it works thanks! Another solution with node 13, but it not works for some reason.
