### ISSUE TITLE
Testing errors with strings not working

### ISSUE THREAD

**Issue by christopheraue** [lorenzofox3/zora#58]
Running the following test file should report a failure but does not:

```
// error.js
const {test} = require('zora')

test('error message with string', t => {
  t.throws(() => { throw new Error('message') }, 'another message')
})
```

Output:
```
$ node error.js 
TAP version 13
# error message with string
ok 1 - another message
1..1

# ok
# success: 1
# skipped: 0
# failure: 0
```

**Comment by lorenzofox3** [comment]
I think the documentation is wrong here or misleading. 

I did not implemented this feature myself but it seems the ``expected`` can not be a string or is [assumed to be the description of the assertion](https://github.com/lorenzofox3/zora/blob/master/test/unit/assertion.js#L261)

You can use regexp instead:
```javascript
  t.throws(() => { throw new Error('message') }, /message/)
```

By accepting a string, I think we would bring too much ambiguity even if we try to detect the number of arguments:
- with one argument is would be clear
- with three arguments it would be clear
- with two it would be unclear: is the last argument the expected value or the description of the assertion

**Comment by christopheraue** [comment]
Ah, ok, I indeed misinterpreted the docs here. Thanks for clearing it up.

**Comment by lorenzofox3** [comment]
I reopen as the doc needs to be taken care of
