### ISSUE TITLE
Question about ESM usage

### ISSUE THREAD

**Issue by bradsimantel** [lorenzofox3/zora#62]
First off, thanks for making an awesome testing library! I just have a quick question:

In the Zora `package.json` there's a `"module"` property with a path to an ESM build that has named exports for every method, but when I `import { test } from "zora";` in my test file (running Node 14.0.0), I get `SyntaxError: The requested module 'zora' does not provide an export named 'test'`. In my `package.json` I've specified `"type": "module"`, but am using .js not .mjs.

I put together a minimal repro [here](https://github.com/bradsimantel/zora-test). It seems that, for whatever reason, Node isn't loading the ESM build but the CommonJS build, because if I `import zora from "zora";` it works and has the expected methods. To reproduce, you can `npm run test` or `yarn run test` in my repro.

Is this expected behavior? Do you know why it's happening?

**Comment by lorenzofox3** [comment]
This was for module bundler back in old days :). We should probably move on to native Node's loader now. I need to deeg a little bit to make sure everything works fine. Should not be complicated. Closed for #63
