### ISSUE TITLE
Support for async functions in throws and doesNotThrow assertions

### ISSUE THREAD

**Issue by Andrew-Fryer** [lorenzofox3/zora#66]
Specifically, I am trying to test that my asynchronous code throws. (In other words, that a promise rejects...) So, I would like the following to work:
```javascript
t.throws(async () => {
  await myAsyncCode();
});
```
This does not currently work because we don't await the function call at https://github.com/lorenzofox3/zora/blob/01e8e1a0c001af33bf45608aee0525e12b7af365/src/assertion.ts#L103

The same is true for `doesNotThrow`.

If this would break code I would like to propose new assertions `resolves` and `rejects` that would accept promises and await them and assert that they resolve or reject respectively.

**Comment by lorenzofox3** [comment]
Thanks, I need to think a bit on how to provide an ergonomic API. 

First idea, maybe check whether ``func`` is promise. In that case we would wait for it. However the caller should write something like: 

```Javascript
await t.throws(myAsycnCode)
```

which makes sense somehow.

As a workaround you can do 

```Javascript
try{
   await asyncCall();
   t.fail('should not reach that code')
} catch (e) {
   // assertions here
   t.eq(e.message, 'something')
}

```

**Comment by Andrew-Fryer** [comment]
Hey, sorry I haven't been around!

Yeah, we used a workaround very similar to the above.

If I have some time in the future maybe I'll take a crack at a PR...

**Comment by acostalima** [comment]
@lorenzofox3 what about `throwsAsync`?

**Comment by davidbonnet** [comment]
https://github.com/kopischke/microESLint.nova seems to handle it for Eslint 6
