### ISSUE TITLE
Only mode

### ISSUE THREAD

**Issue by davidrot** [lorenzofox3/zora#69]
I would like to ask for some advice how I can get the only mode working when using a test watch command. The command is watching all files for changes, if so the tests are executed. The command is running all the time while I'm implementing. When I'm using now the only method I get an exception during the execution and I have to restart the command. This is not a good workflow. 

Have you any ideas how I can achieve this? 
How is it behaving if I'm running in only mode without having only tests?
How can I set the only mode running inside a browser? 

Thanks in advance!

**Comment by lorenzofox3** [comment]
With node, if you want to run in only mode you have to set the env variable ``RUN_ONLY=true`` before your run your test (and unset it needed). It throws to avoid to push code with ``.only`` calls (make the CI fail). 
For example if you watch your files with nodemon, in the same terminal:

```bash
export RUN_ONLY=true;
nodemon ./test/index.js
```
assuming you have something like: 
```javascript
// ./test/test-1.js
import {only} from 'zora';

only(`hello test-1`, (t) =>{
    t.ok(true);
})

// ./test/test-2.js
import {test} from 'zora';

test(`hello test-2`, (t) =>{
    t.ok(true);
})

// test/index.js

import './test-1.js';
import './test-2.js';
```

(Alternatively you can use [pta, the node test runner](https://github.com/lorenzofox3/zora-node))

For the browser, the environment is set with a global variable. I don't know how you load/watch your files in the browser (if you bundle them first, use a dev server, etc) but you can have something similar to:
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    window.RUN_ONLY=true;
</script>
<script type="module">
    import './test/index.js';
</script>
</body>
</html>
```

And look at the console when visiting this page.

**Comment by davidrot** [comment]
> It throws to avoid to push code with .only calls (make the CI fail).

I think this is a good feature but makes zora with current implementation more unflexible.
I think the ci fail behavior should activated via an environment flag and in the default execution when there are only tests, only those should executed. I think the most test-frameworks have such an only behavior.

**Comment by lorenzofox3** [comment]
Well it is an opt-in solution rather than a opt-out. I find this more rational in the sense that ``only`` has no really meaning regarding the testing program. It is more a convenience for the developer. You'll find more details [here](https://github.com/lorenzofox3/zora/issues/16). 

I am closing this. If you have further questions, feel free to fill another issue. 

Thanks for your contribution
