### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by corbinu** [lorenzofox3/zora#7]
Super excited to see this honestly have spent the last month looking for a new testing framework and this looks amazing. Would you be open to if I committed a type definition set?

**Comment by lorenzofox3** [comment]
hey sorry for the late reply I was in vacation. Sure. However please note I am currently working on a version 2 which will have exactly the same API than other tap frameworks such node-tap or tape (to make thing easier). Cheers

**Comment by corbinu** [comment]
@lorenzofox3 No worries. Actually I ended up forking for the short term especially since the current default export is not compatible with es2015 Modules. Also I wanted to be able to transpile it to es3 so could do some browser tests in older versions of IE plus I wanted to add a few small features. Total lines still about the same. Happy to collaborate if your interested.

**Comment by lorenzofox3** [comment]
> default export is not compatible with es2015 Module

can you elaborate please ?

**Comment by corbinu** [comment]
Sorry better way to put it is that an es2015 module can’t be just a function. A function can be the default export however. 

Babel breaks the spec to get around this and there is some debate as to what all the changes will be to get node to support ES modules. However TypeScript makes it a rule to stay with the spec on everything. So in my version I changed it to just be ES modules and then used TypeScript to transpile down to ES3 and commonjs. 

However the problem could be fixed a few other ways including just mapping the module.exports to module.exports.default

 Happy to open a PR if you like.

**Comment by corbinu** [comment]
@lorenzofox3 Does that make more sense? Get why you want to go more towards the tap API however.

**Comment by lorenzofox3** [comment]
> Sorry better way to put it is that an es2015 module can’t be just a function. A function can be the default export however.

I am not sure ? 

what about:

```Javascript
// myModule.js
export default function(){}
```
seems legit according to the [spec](https://tc39.github.io/ecma262/#prod-ExportDeclaration)

And indeed next api will be a single function
```
import test from 'zora';

test('foo', t=>{
  t.ok(true);
})
```

I should be done by the end of the week. I'll send you a notif for a beta review when I am done ;)

**Comment by corbinu** [comment]
Nvm your right your my fault actually looks like it was a bug in rollup when it was going the conversion to commonjs that has since been fixed.

**Comment by lorenzofox3** [comment]
@corbinu The new pre major release is available. Can you try a little bit and tell me what you think ? Thanks

**Comment by corbinu** [comment]
Sure will do!

**Comment by styfle** [comment]
I would be interested in typescript definitions 👍 

I got referred to this project from `tape-modern` here: https://github.com/Rich-Harris/tape-modern/issues/2

**Comment by lorenzofox3** [comment]
@styfle 

great timing, I am in the process of writing the code base in typescript. I'll let you know when I have a branch so you can review it.

**Comment by corbinu** [comment]
@lorenzofox3 Are you still rewriting in TypeScript? I was thinking about taking a stab at writing a version in Rust that would compile to WASM+TypeScript as kinda a test project.

Corbin

**Comment by lorenzofox3** [comment]
yes sorry. I started again this vacations: [v3](https://github.com/lorenzofox3/zora/tree/v3) is being written in typescript

**Comment by corbinu** [comment]
no need to be sorry at all! we all get busy thanks for your hard work!
