### ISSUE TITLE
Add option to allow to remove the duration of subtest's execution from the TAP output

### ISSUE THREAD

**Issue by acostalima** [lorenzofox3/zora#75]
While running Zora in React Native and to make sure the indent option is being propagated correctly to the runtime, I'm taking a snapshot of the tap output. The problem with this approach is that the snapshot becomes fragile as the number of milliseconds it takes to execute a subtest can easily change between runs.

**Comment by lorenzofox3** [comment]
Hi and Thanks for the contribution. 
I don't think it is worthwile to clutter the code with more options and code. The whole point of using UNIX text stream interfaces like TAP is to allow some other tool to process downstream. In your case you can simply use ``sed``
``node test.js | sed 's/[0-9]\{1,\}ms/TIME/g'`` And you will get all the execution time replaced with "TIME"

**Comment by acostalima** [comment]
@lorenzofox3 sounds great, thanks! 💪
