### ISSUE TITLE
Codepen link is broken

### ISSUE THREAD

**Issue by oles** [lorenzofox3/zora#8]
From README.md:

> You can for example play with this [codepen](http://codepen.io/lorenzofox3/pen/zoejxv?editors=1112)

Fixed it in this fiddle: https://codepen.io/anon/pen/mXOwvQ

**Comment by lorenzofox3** [comment]
Thanks

**Comment by oles** [comment]
Ref https://github.com/lorenzofox3/zora/issues/11, it seems like this will be fixed in V2 👌
