### ISSUE TITLE
Break object cycles in JSON output

### ISSUE THREAD

**Issue by mindplay-dk** [lorenzofox3/zora#87]
I keep getting errors like this one in my tests:

```
> node test/test.js | tap-diff

(node:5272) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Array'
    |     index 0 -> object with constructor 'Text'
    |     property 'parentNode' -> object with constructor 'Element'
    --- property 'childNodes' closes the circle
    at JSON.stringify (<anonymous>)
    at Object.printYAML (file:///mnt/c/workspace/diff/node_modules/zora/dist/bundle/index.mjs:465:41)
    at Object.printAssertion (file:///mnt/c/workspace/diff/node_modules/zora/dist/bundle/index.mjs:490:22)
    at Object.report (file:///mnt/c/workspace/diff/node_modules/zora/dist/bundle/index.mjs:516:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

In this particular case, it's a test-dependency ([undom](https://github.com/developit/undom)) which contains a cycle, e.g. from elements in `childNodes` to their `parentNode` references, and back.

The reporter is calling out to `JSON.stringify` directly, which [doesn't handle cycles](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value) - not very helpful in diagnostic output.

There's a very old (and simple) solution [here](https://github.com/douglascrockford/JSON-js/blob/master/cycle.js), which will convert cycles to e.g. `{"$ref": "..."}` with a generated JSON-path specifier. That might work, although the purpose of this isn't for diagnostic output, but rather so you can encode object structures with cycles and decode them again, restoring the object cycles.

Simply replacing cycles with `undefined` is another option.

But no matter what you do to preprocess the data structure itself, it won't resemble the original data structure - so either way, this could be quite confusing.

This problem applies to errors, not to failing tests - so I don't think we can just say it's up to the reporter? And I don't think you would really want this concern left up to individual reporters either? It's a cross-cutting concern for all reporters, so probably should be handled at the framework level. (?)

I looked at a few different libraries, and this one looks reasonably simple:

https://github.com/inspect-js/object-inspect

It handles many edge-cases for JavaScript that JSON does not, including [cycles](https://github.com/inspect-js/object-inspect/blob/master/test/circular.js), [arrays with holes](https://github.com/inspect-js/object-inspect/blob/master/test/holes.js) and [DOM elements](https://github.com/inspect-js/object-inspect/blob/master/test/browser/dom.js).

It's around 400 LOC or 7K minified, 3K gzipped - not sure how you measure your footprint, but I'm pretty sure zora would still be the smallest test-framework regardless.

What do you think about integrating this? (or something like it?)

**Comment by lorenzofox3** [comment]
The problem lies in the [reporter package](https://github.com/lorenzofox3/zora-reporters). 

The footprint is quite high (more than 50% of actual code size) but I don't mind as long it is useful (which might be the case here). 

But I think there is a disign issue here to fix first: the reporter should allow a different serializer/logger to be configured by the calling code defaulting to JSON.stringify/console.log (eventullay to the lib you mentionned). So we need to address this first

**Comment by lorenzofox3** [comment]
should be fix in v5 branch
