### ISSUE TITLE
Stopping a sequenced test

### ISSUE THREAD

**Issue by oles** [lorenzofox3/zora#9]
This library is such a breath of fresh air - really well done! 

Currently I'm trying to create a integration/functional/semi-e2e test, using the "{sequence: true}" option. 
I'd like for the test to "fail-fast", like in AVA's --fail-fast option (https://github.com/avajs/ava#cli), aka "Stop after first test failure".

However, it seems like you're currently on to something that will solve this: https://github.com/lorenzofox3/zora/issues/7#issuecomment-362608776: 

> I am currently working on a version 2 which will have exactly the same API than other tap frameworks such node-tap or tape

Creating this issue so that version 2 will hopefully feature this 👍

**Comment by lorenzofox3** [comment]
Yes, you can also use a tap-reporter which bail out on first failing test. [tap-bail](https://github.com/juliangruber/tap-bail) is an example

**Comment by oles** [comment]
Awesome! Thanks for the suggestion :)
