### ISSUE TITLE
INDENT=true is not working in zora@5.0.0-alpha.3

### ISSUE THREAD

**Issue by Abdelaziz18003** [lorenzofox3/zora#92]
Hey there, this is my first time using zora. Thanks for this great tool.

I found that `INDENT=true` is not working in zora@5.0.0-alpha.3. Below is the raw TAP output of running the example test file.

![2021-05-29_00-35](https://user-images.githubusercontent.com/11301627/120051143-5d7a2980-c017-11eb-86fd-f30f1920e58a.png)

**Comment by lorenzofox3** [comment]
You are right, this is not available in the v5 pre releases. If you wish to use it, you 'll need to stick to the latest stable release (v4)
